In [2]:
import numpy as np

from vector_packing import cvx_condense
from vector_packing import brute_force_condense

import warnings
warnings.filterwarnings("ignore")

%load_ext autoreload
%autoreload 2

In [12]:
""" For reproducing results"""
np.random.seed(1)

""" N-dimensional bin packing problem input data"""
# vec_length = 60000
vec_length = 10
density_setup = 0.25
vt_bit_map = np.random.binomial(1, density_setup, (vec_length, 16)).astype(np.uint32)
print(vt_bit_map)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0]
 [1 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0]
 [1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0]
 [1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1]]


In [13]:
brute_force_condense(vt_bit_map)

N_BOXES USED:  6


array([0, 1, 0, 1, 2, 2, 3, 4, 5, 5])

In [23]:
cvx_condense(vt_bit_map)

                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Sep 22 05:46:49 PM: Your problem has 110 variables, 18 constraints, and 0 parameters.
(CVXPY) Sep 22 05:46:49 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Sep 22 05:46:49 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Sep 22 05:46:49 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Sep 22 05:46:49 PM: Compiling problem (target solver=CBC).
(CVXPY) Sep 22 05:46:49 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -

array([4, 5, 3, 2, 7, 2, 1, 4, 2, 5], dtype=int32)